* ox-w3ctr --- org export backend for W3C TR CSS style

Based on Org-mode's ox-html.el and CSS of W3C Technical Report [[https://github.com/w3c/tr-design][tr-design]]'s base.css.

** Status

| Emacs Version   |         30.1 |         31.1 |  32.1 |
|-----------------+--------------+--------------+-------|
| Package Version |          0.2 |          0.3 |   1.0 |
| Date            | [2025-02-23] | [2026-08-24] | 2027? |

The current ox-w3ctr has not yet completed a full refactoring of the
ox-html code, though it’s already largely usable. I plan to release
version 1.0 when Emacs 32.1 comes out.

When version 1.0 is released, the package should no longer introduce
breaking changes, and Emacs 32.1 will be the minimum supported
version. In a sense, 1.0 will be the first official release. If more
users and bug reports come in, this process from 0.4 to 1.0 might move
faster.

** Install and Use

Please use Emacs 32.0.50 or above. Download this repo and add it to
=load-path=, or use =package-vc= like this:

#+begin_src text
M-x package-vs-install https://github.com/include-yy/ox-w3ctr RET
#+end_src

After installation and load, use =C-c C-e w o= to export a org buffer to
HTML file. See more information from docstrings and comments (at least
now).

** =TODO= list [0/4]

1. [ ] Totally Refactor from ox-html.
2. [ ] Fully detailed documentation.
3. [ ] A friendly introductive video.
4. [ ] CI/CD support.
